### ISSUE TITLE
Recursion error when with bfgz files

### ISSUE THREAD

**Issue by arivers** [mdshw5/pyfaidx#131] opened 2018-01-05 17:51 UTC
This issue relates to [issue #125](https://github.com/mdshw5/pyfaidx/issues/125). When accessing a 299GB bfgz fasta file created by Pbgzip, I encounter a recursion error that comes from the Biopython module bfgz.

```Python
  File "/global/homes/a/arrivers/.conda/envs/vicaenv/lib/python3.6/site-packages/pyfaidx/__init__.py", line 574, in from_file
    chunk_seq = self.file.read(chunk).decode()
  File "/global/homes/a/arrivers/.conda/envs/vicaenv/lib/python3.6/site-packages/Bio/bgzf.py", line 655, in read
    return data + self.read(size)
  File "/global/homes/a/arrivers/.conda/envs/vicaenv/lib/python3.6/site-packages/Bio/bgzf.py", line 655, in read
    return data + self.read(size)
  File "/global/homes/a/arrivers/.conda/envs/vicaenv/lib/python3.6/site-packages/Bio/bgzf.py", line 655, in read
    return data + self.read(size)
  [Previous line repeated 979 more times]
  File "/global/homes/a/arrivers/.conda/envs/vicaenv/lib/python3.6/site-packages/Bio/bgzf.py"0, line 648, in read
    self._load_block()  # will reset offsets
  File "/global/homes/a/arrivers/.conda/envs/vicaenv/lib/python3.6/site-packages/Bio/bgzf.py", line 577, in _load_block
    block_size, self._buffer = _load_bgzf_block(handle, self._text)
  File "/global/homes/a/arrivers/.conda/envs/vicaenv/lib/python3.6/site-packages/Bio/bgzf.py", line 412, in _load_bgzf_block
    if magic != _bgzf_magic:
RecursionError: maximum recursion depth exceeded in comparison
```
My Pyfaidx version is 0.5.1 from bioconda and my Biopython version is 1.70 installed from pip.

**Comment by mdshw5** [comment] 2018-01-06 17:51
Hmmm. This is interesting. @peterjc left a hint about avoiding recursion in the `readline` method that's causing this `RecursionError`:

https://github.com/biopython/biopython/blob/477f69aeb4570d5b6c20c43c7eee685e16951ee2/Bio/bgzf.py#L653-L678

My guess, from looking at the `bgzf` code, is that your 299GB (!!!) file has really, really long lines, or maybe the file is corrupted at a line break.

**Comment by mdshw5** [comment] 2018-01-06 17:53
Adding @KwatME since he raised this issue earlier as well.

**Comment by peterjc** [comment] 2018-01-07 00:15
From skimming that section of my code (``Bio/bgzf.py``), I would guess this file has a really really long line as @mdshw5 suggests. I take it this is a BGZF compressed FASTA file, so this could be a very long sequence like an entire chromosome with no line breaks?

It should be trivial to confirm (or reject) this guess, perhaps as simple as:

```python
import gzip
handle = gzip.open('problem-file.gz')
for line in handle:
    if len(line) > 100: 
        print(len(line))
handle.close()
```

Is there a public copy of this problem file?

Can you reduce this to test case using just ``bgzf.py`` (and not ``pyfaidx`` as well)? If so we may want to log this as a bug over on Biopython.

Peter

**Comment by peterjc** [comment] 2018-01-07 00:17
I presume from the details on #125 that @KwatME was using this file:

http://ftp.ensembl.org/pub/current_fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

**Comment by mdshw5** [comment] 2018-01-07 03:51
Updated #125 - was able to reproduce the issue there.

**Comment by peterjc** [comment] 2018-07-02 09:54
Can we close #131 as a duplicate of #125?

**Comment by mdshw5** [comment] 2018-07-03 15:42
Yes I'll close this as it is a duplicate of #125

**Closed by mdshw5** 2018-07-03 15:42 UTC

**Comment by arivers** [comment] 2018-09-27 17:14
Thanks @mdshw5  and @peterjc  for fixing this recursion error.  I look forward to trying out the new improved pyfaidx.

**Comment by peterjc** [comment] 2018-09-27 21:10
Most of the credit goes to @rtf-const for refactoring my recursive functions into loops, but multiple people have helped too. We'd best get the new Biopython release out soon so you can all use this more easily.
