### ISSUE TITLE
Indexing [0:0] is different than standard Python string

### ISSUE THREAD

**Issue by vejnar** [mdshw5/pyfaidx#53] opened 2015-03-03 00:16 UTC
```python
>>> gfasta = pyfaidx.Fasta('....fa', as_raw=True)
>>> gfasta['chr1'][0:0]
```
Returns the whole chromosome

```python
>>> s='ABCD'
>>> s[0:0]
```
Returns an empty string

IMHO, pyfaidx should return an empty string.

**Comment by mdshw5** [comment] 2015-03-03 02:23
I wholeheartedly agree, and will make this the expected behavior in the next release.

**Comment by mdshw5** [comment] 2015-03-03 03:31
It looks like this is now fixed and will be included the next time I push a release. Thanks!

**Closed by mdshw5** 2015-03-03 03:31 UTC
Labels: bug
